{% set version = "4.19.8" %}

package:
  name: sip
  version: {{ version }}

source:
  fn:   sip-{{ version }}.tar.gz
  url:  http://sourceforge.net/projects/pyqt/files/sip/sip-{{ version }}/sip-{{ version }}.tar.gz
  sha256: 7eaf7a2ea7d4d38a56dd6d2506574464bddf7cf284c960801679942377c297bc

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - python
  run:
    - python

test:
  imports:
    - sip
  files:
    - test

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL-3.0
  license_file: LICENSE
  summary: Create Python bindings for C and C++ libraries
  description: |
    SIP is a tool that makes it very easy to create Python bindings for C and
    C++ libraries. SIP comprises a code generator and a Python module. The
    code generator processes a set of specification files and generates C or
    C++ code which is then compiled to create the bindings extension module.
    The SIP Python module provides support functions to the automatically
    generated code.
  doc_url: http://pyqt.sourceforge.net/Docs/sip4/
  dev_url: https://github.com/ifwe/sip

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
