{% set version = "4.19.20" %}

package:
  name: sip
  version: {{ version }}

source:
  url:  https://www.riverbankcomputing.com/static/Downloads/sip/{{ version }}/sip-{{ version }}.tar.gz
  sha256: 04cc2f87ac97e8718d8e1ef036e3ec26050ab44c21f9277618d5b67432fcbfd6
  patches:
    - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
  host:
    - python
  run:
    - python

test:
  requires:
    - {{ compiler('cxx') }}
    - make  # [not win]
  imports:
    - sip
  files:
    - test

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL-3.0
  license_file: LICENSE
  summary: Create Python bindings for C and C++ libraries
  description: |
    SIP is a tool that makes it very easy to create Python bindings for C and
    C++ libraries. SIP comprises a code generator and a Python module. The
    code generator processes a set of specification files and generates C or
    C++ code which is then compiled to create the bindings extension module.
    The SIP Python module provides support functions to the automatically
    generated code.
  doc_url: http://pyqt.sourceforge.net/Docs/sip4/
  dev_url: https://github.com/ifwe/sip

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
    - ocefpaf
